### ISSUE TITLE
Help for the ex06 Diff (day00)

### ISSUE THREAD

**Issue by cristianoromaldetti** [evgenkarlson/Completed___Piscine_C___of___School_42#1]
Hi, i'm Cristiano from Italy, i will start the piscine very soon, so was looking around to in order to exercise a bit before i go.

i can't achieve the Diff exercise, i think i do the right things but my b file is still THE SAME as the a file...
i don't understand how can diff + patch modify the text in that way... maybe i'm losing somenting..
can you help me ?

my path was : 

touch a b 
cat > a 
(all the starwars text)

cat -e a > b

diff a b > sw.diff

patch b sw.diff

the result sucks, a lot, and i read the man of patch like 15 times only today..

Thanks !

**Comment by lalaloka** [comment]
Hi man.when u will be on your piscine in Intra u u should download two files for this exercise.so the main problem now is that u dont have them))it will be "a" and "dif"then u should just patch "a" with "diff"my main advice is to understand poiners in C..good luck man!)-------- Исходное сообщение --------От: C-Sylar <notifications@github.com>Дата: пт, 25 сент. 2020 г., 20:41Кому: evgenkarlson/Completed___Piscine_C___of___School_42 <Completed___Piscine_C___of___School_42@noreply.github.com>Копия: Subscribed <subscribed@noreply.github.com>Тема: [evgenkarlson/Completed___Piscine_C___of___School_42] Help for the ex06 Diff (day00) (#1)
Hi, i'm Cristiano from Italy, i will start the piscine very soon, so was looking around to in order to exercise a bit before i go.
i can't achieve the Diff exercise, i think i do the right things but my b file is still THE SAME as the a file...
i don't understand how can diff + patch modify the text in that way... maybe i'm losing somenting..
can you help me ?
my path was :
touch a b
cat > a
(all the starwars text)
cat -e a > b
diff a b > sw.diff
patch b sw.diff
the result sucks, a lot, and i read the man of patch like 15 times only today..
Thanks !

**Comment by cristianoromaldetti** [comment]
F***K !! thanks man, i'm going crazy.
 thanks for the advice, i will do it
see ya!
